routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AreaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::resources([
    'users'     => UserController::class,
    'documents' => DocumentController::class,
    'areas'     => AreaController::class
]);

Route::get('/generate_email/{email}', [UserController::class, 'generateEmail'])->name('generate_email');

resources/views/partials/footer.blade.php
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <div class="float-start">
            <span class="text-muted">Sistema de gestión de empleados de <strong>Cidente S.A.S</strong>.</span>
        </div>
        <div class="float-end ml-4 text-center text-sm text-gray-500 sm:text-right sm:ml-0">
            Laravel v{{ Illuminate\Foundation\Application::VERSION }} (PHP v{{ PHP_VERSION }})
        </div>
    </div>
</footer>

resources/views/partials/header.blade.php
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
        <div class="container">
            <a class="navbar-brand" href="{{ route('home') }}">
                <img src="{{ asset('images/cidenet-logo.png') }}" class="img-fluid  w-25 h-25" alt="Logo de Cidenet S.A.S">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a href="{{ route('home') }}" class="nav-link {{ ! Route::is('home') ?: 'active' }}">
                            <i class="fa-solid fa-house"></i> Inicio
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('areas.index') }}" class="nav-link {{ ! Route::is('areas.*') ?: 'active' }}">
                            <i class="fa-solid fa-building"></i> Áreas
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('documents.index') }}" class="nav-link {{ ! Route::is('documents.*') ?: 'active' }}">
                            <i class="fa-solid fa-id-card"></i> Documentos
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('users.index') }}" class="nav-link {{ ! Route::is('users.*') ?: 'active' }}">
                            <i class="fa-solid fa-users"></i> Usuarios
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

resources/views/partials/notification.blade.php
<div class="row">
    <div class="col">
        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <p class="mb-0">
                    <i class="fa-solid fa-check-double"></i> {{ $message }}
                </p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
    </div>
</div>