routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AreaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::resources([
    'users'     => UserController::class,
    'documents' => DocumentController::class,
    'areas'     => AreaController::class
]);

Route::get('/generate_email/{email}', [UserController::class, 'generateEmail'])->name('generate_email');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use App\Models\Area;
use App\Models\Document;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model's ID is auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'second_name',
        'first_lastname',
        'second_lastname',
        'country',
        'document_id',
        'number_document',
        'email',
        'date_admission',
        'area_id',
        'status'
    ];
  
    /**
     * document
     *
     * @return void
     */
    public function document()
    {
        return $this->hasOne(Document::class, 'foreign_key', 'local_key');
    }
    
    /**
     * area
     *
     * @return void
     */
    public function area()
    {
        return $this->hasOne(Area::class, 'foreign_key', 'local_key');
    }
    
    /**
     * scopeFirstName
     *
     * @param  mixed $query
     * @param  mixed $first_name
     * @return void
     */
    public function scopeFirstName($query, $first_name)
    {
        if (trim($first_name) || !empty($first_name))
            return $query->where('first_name', 'LIKE', '%'.$first_name.'%')
                         ->orderBy('first_name', 'asc');
    }

    /**
     * scopeSecondName
     *
     * @param  mixed $query
     * @param  mixed $second_name
     * @return void
     */
    public function scopeSecondName($query, $second_name)
    {
        if (trim($second_name) || !empty($second_name))
            return $query->where('second_name', 'LIKE', '%'.$second_name.'%')
                         ->orderBy('second_name', 'asc');
    }
    
    /**
     * scopeFirstLastName
     *
     * @param  mixed $query
     * @param  mixed $first_lastname
     * @return void
     */
    public function scopeFirstLastName($query, $first_lastname)
    {
        if (trim($first_lastname) || !empty($first_lastname))
            return $query->where('first_lastname', 'LIKE', '%'.$first_lastname.'%')
                         ->orderBy('first_lastname', 'asc');
    }

    /**
     * scopeEmail
     *
     * @param  mixed $query
     * @param  mixed $email
     * @return void
     */
    public function scopeEmail($query, $email)
    {
        if (trim($email) || !empty($email))
            return $query->where('email', 'LIKE', '%'.$email.'%');
    }

    /**
     * scopeTypeDocument
     *
     * @param  mixed $query
     * @param  mixed $document_id
     * @return void
     */
    public function scopeTypeDocument($query, $document_id)
    {
        if (trim($document_id) || !empty($document_id))
            return $query->where('document_id', 'LIKE', '%'.$document_id.'%');
    }

    /**
     * scopeNumberDocument
     *
     * @param  mixed $query
     * @param  mixed $number_document
     * @return void
     */
    public function scopeNumberDocument($query, $number_document)
    {
        if (trim($number_document) || !empty($number_document))
            return $query->where('number_document', 'LIKE', '%'.$number_document.'%');
    }

    /**
     * scopeStatus
     *
     * @param  mixed $query
     * @param  mixed $status
     * @return void
     */
    public function scopeStatus($query, $status)
    {
        if (trim($status) || !empty($status))
            return $query->where('status', 'LIKE', '%'.$status.'%');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Document;
use App\Models\Area;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $documents = Document::all();
        $areas     = Area::all();

        return view('users.create', compact('documents', 'areas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreUserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        $validatedData = $request->validated();

        User::create($validatedData->all());

        return redirect()->route('users.index')->with('success','Usuario creado exitosamente !!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateUserRequest  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $validatedData = $request->validated();

        $user->updateOrCreate($validatedData->all());

        return redirect()->route('users.index')->with('success','Usuario updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('users.index')->with('success','user deleted successfully');
    }
                
    /**
     * generateEmail
     *
     * @param  mixed $first_name
     * @param  mixed $first_lastname
     * @param  mixed $email
     * @param  mixed $country
     * @return void
     */
    public function generateEmail(String $first_name, String $first_lastname, String $email, String $country)
    {
        $currentEmail = User::email($email);

        if ( $country === 'colombia' )
            $domain = 'cidenet.com.co';
        
        if ( $country === 'estados unidos' )
            $domain = 'cidenet.com.us';

        if ( $currentEmail )
            $newEmail = $first_name . '.' . $first_lastname . '@' . $domain;
        

        return $newEmail;
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Usuario nuevo')

@section('content')

    <div class="row">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-header text-bg-dark">
                    <div class="float-start">
                        <a class="btn btn-outline-primary" href="{{ route('users.index') }}">
                            <i class="fa-solid fa-arrow-rotate-left"></i> Atrás
                        </a>
                    </div>
                    <div class="float-end">
                        <h4>Nuevo Usuario</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('users.store') }}" method="POST" class="needs-validation" novalidate>
                        @csrf

                        <div class="row">
                            <div class="col">
                                <div class="mb-3">
                                    <label for="first_name" class="form-label">Primer Nombre</label>
                                    <input type="text" name="first_name" class="form-control @error('first_name') is-invalid @enderror" placeholder="Primer Nombre">
                                    @error('first_name')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label for="second_name" class="form-label">Segundo Nombre</label>
                                    <input type="text" name="second_name" class="form-control @error('second_name') is-invalid @enderror" placeholder="Otro Nombre">
                                    @error('second_name')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label for="first_lastname" class="form-label">Primer Apellido</label>
                                    <input type="text" name="first_lastname" class="form-control @error('first_lastname') is-invalid @enderror" placeholder="Primer Apellido">
                                    @error('first_lastname')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label for="second_lastname" class="form-label">Segundo Apellido</label>
                                    <input type="text" name="second_lastname" class="form-control @error('second_lastname') is-invalid @enderror" placeholder="Segundo Apellido">
                                    @error('second_lastname')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="mb-3">
                                    <label for="country" class="form-label">País</label>
                                    <select class="form-select @error('country') is-invalid @enderror" aria-label="country">
                                        <option value="">Seleccionar</option>
                                        <option value="colombia">Colombia</option>
                                        <option value="estados unidos">Estados Unidos</option>
                                    </select>
                                    @error('country')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label for="document_id" class="form-label">Tipo de documento</label>
                                    <select class="form-select @error('document_id') is-invalid @enderror" aria-label="country">
                                        <option value="">Seleccionar</option>
                                        @foreach ($documents as $document)
                                            <option value="{{ $document->id }}" @selected(old('document->id') == $document->id)>
                                                {{ $document->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('document_id')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label for="number_document" class="form-label">Número de documento</label>
                                    <input type="text" name="number_document" class="form-control @error('number_document') is-invalid @enderror" placeholder="Número de documento">
                                    @error('number_document')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label for="area_id" class="form-label">Área</label>
                                    <select class="form-select @error('area_id') is-invalid @enderror" aria-label="area_id">
                                        <option value="">Seleccionar</option>
                                        @foreach ($areas as $area)
                                            <option value="{{ $area->id }}" @selected(old('area->id') == $area->id)>
                                                {{ $area->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('area_id')
                                        <div class="invalid-feedback">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-end">
                            <div class="col-3">
                                <div class="d-grid gap-2">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa-solid fa-floppy-disk"></i> Agregar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Editar Documento')

@section('content')

    <div class="row">
        <div class="col-md-6 offset-md-3">
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <ul class="list-unstyled mb-0">
                        @foreach ($errors->all() as $error)
                            <li><i class="fa-solid fa-circle-exclamation"></i> {{ $error }}</li>
                        @endforeach
                    </ul>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow-sm">
                <div class="card-header text-bg-dark">
                    <div class="float-start">
                        <a class="btn btn-outline-primary" href="{{ route('documents.index') }}">
                            <i class="fa-solid fa-arrow-rotate-left"></i> Atrás
                        </a>
                    </div>
                    <div class="float-end">
                        <h4>Editar Documento</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('documents.update', $document->id) }}" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="mb-3 row">
                            <label for="name" class="col-sm-2 col-form-label">Nombre</label>
                            <div class="col-sm-10">
                                <input type="text" name="name" class="form-control" placeholder="Nombre del documento" value="{{ $document ? $document->name : '' }}">
                            </div>
                        </div>

                        <div class="mb-3 row justify-content-end">
                            <div class="col-4">
                                <div class="d-grid gap-2">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa-solid fa-pen"></i> Editar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Lista de Usuarios')

@section('content')

    <div class="row">
        <div class="col">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <p class="mb-0">
                        <i class="fa-solid fa-check-double"></i> {{ $message }}
                    </p>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-header text-bg-dark">
                    <div class="float-start">
                        <h4><i class="fa-solid fa-list"></i> Usuarios</h4>
                    </div>
                    <div class="float-end">
                        <a class="btn btn-outline-primary" href="{{ route('users.create') }}">
                            <i class="fa-solid fa-plus"></i> Nuevo
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr class="text-center">
                                <th>#</th>
                                <th>Primer Nombre</th>
                                <th>Segundo Nombre</th>
                                <th>Primer Apellido</th>
                                <th>Otros Nombres</th>
                                <th>País</th>
                                <th>Tipo documento</th>
                                <th># de documento</th>
                                <th>Correo</th>
                                <th>Fecha de ingreso</th>
                                <th>Área</th>
                                <th>Estado</th>
                                <th>Fecha Creado</th>
                                <th>Hora Creado</th>
                                <th>Acción</th>
                            </tr>
                        </thead>
                        <tbody>
                           
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('title', 'Detalle del documento')

@section('content')

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow-sm">
                <div class="card-header text-bg-dark">
                    <div class="float-start">
                        <a class="btn btn-outline-primary" href="{{ route('documents.index') }}">
                            <i class="fa-solid fa-arrow-rotate-left"></i> Atrás
                        </a>
                    </div>
                    <div class="float-end">
                        <h4>Tipo de Documento</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="mb-3 row">
                        <label for="name" class="col-sm-2 col-form-label">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" name="name" class="form-control" value="{{ $document ? $document->name : '' }}" readonly disabled>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection